// Code that generators the random lorem ipsum text

// Create a new object called loremIpsum by invoking the GenerateNewText constructor function
const loremIpsum = new GenerateNewText();

// Constructor function that creates an object with the words property
function GenerateNewText() {
  // Add property to the object
  this.sentences =
    [
      
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis magna vitae tellus fringilla accumsan. Maecenas rutrum varius est, et eleifend nisi egestas sodales. Duis ut blandit ipsum. Praesent egestas libero ac mauris tempus scelerisque. Sed tellus arcu, imperdiet ut elit sit amet, aliquet aliquam metus. Etiam vitae metus nec nisl tempus aliquet. Cras elementum faucibus ex non placerat. Etiam velit mauris, rutrum vitae neque id, dapibus tincidunt eros.",
      "Duis venenatis diam eget semper molestie. Sed at elementum magna, rhoncus tincidunt neque. Aliquam rutrum purus lectus, pharetra dictum neque hendrerit vel. Sed congue eget risus at rhoncus. Quisque id dapibus tortor. Cras hendrerit vel massa nec euismod. Nulla sed laoreet purus, non tincidunt eros. Morbi at vehicula nisl, quis fermentum lorem. Maecenas elementum ante sit amet neque dictum rutrum. Mauris at augue consequat, maximus sem non, bibendum felis. Mauris vel convallis sem, nec viverra odio. Aenean condimentum faucibus dapibus. Fusce pretium ut tellus nec maximus. Cras lacinia tortor sed tellus tempor, ut posuere ligula imperdiet. Duis nec risus vel nibh tincidunt elementum. Integer pharetra sem quis ultricies finibus.",
      "Nulla suscipit leo aliquet, vulputate ipsum in, malesuada nibh. Praesent iaculis hendrerit ultrices. Duis ac ex condimentum tellus mollis fringilla. Aliquam fringilla scelerisque nulla, a bibendum sem tincidunt eget. Vestibulum tempor velit vel magna eleifend pharetra. Curabitur et ipsum nisi. Mauris ultricies pretium turpis, ut mollis nisl.",
      "Sed sagittis nisl sed lacus rutrum tincidunt. Donec turpis risus, efficitur id pellentesque ut, gravida ac nibh. Sed maximus dolor non dui mollis, et consectetur eros bibendum. In ut pretium ligula, ut aliquet ligula. Sed et dui in lorem congue varius eu mollis augue. Nullam ac nisi ipsum. Nullam aliquam magna nec ultrices laoreet. Aenean vitae ex in est ornare congue eget quis enim. Aenean pulvinar lacus mauris, eu tempor felis fermentum eu. Etiam finibus molestie ipsum, in congue sem cursus et. Pellentesque cursus tellus finibus ex aliquet tempus.",
      "Morbi convallis eu diam eget tristique. Curabitur id bibendum ipsum. Mauris dignissim posuere enim ut venenatis. Aliquam sit amet vehicula purus, id fringilla nisi. Duis pellentesque rutrum urna sit amet mattis. Etiam vitae augue at neque viverra interdum quis nec libero. Phasellus ornare nunc condimentum, malesuada justo sit amet, volutpat est. Donec egestas eu lorem ut vehicula. Ut feugiat pellentesque mattis.",
      "Aliquam non tincidunt metus. Nunc a elit metus. Integer nec justo enim. Curabitur tincidunt vel ante in consequat. Donec fringilla eleifend est, quis eleifend nulla rhoncus ac. Sed ultrices auctor eleifend. Curabitur et quam augue. Duis scelerisque nisi in odio hendrerit rutrum. Nunc semper nunc vel metus porta, nec sollicitudin mauris blandit. Phasellus id malesuada purus. Vivamus feugiat sed eros non ultrices. Phasellus rhoncus varius accumsan. Quisque ornare posuere molestie. Duis commodo aliquet nulla, vel gravida ante congue quis. Etiam facilisis dictum urna, vel laoreet ex volutpat eget.",
      "Donec maximus enim ac lobortis luctus. Praesent at rutrum dui, ac rutrum augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi eu elit quis eros feugiat efficitur nec at dolor. Vestibulum cursus risus ac ligula cursus fringilla. Cras id aliquam diam, non elementum metus. Sed sagittis vulputate metus vel fringilla.",
      "Vivamus mi elit, porta vitae risus interdum, egestas eleifend magna. Maecenas eget lobortis mi. Praesent tincidunt viverra nulla. Sed congue augue convallis eleifend aliquam. Nam aliquam eros laoreet sem molestie tempor. Ut lobortis porttitor augue blandit molestie. Sed justo magna, cursus nec blandit in, fermentum vitae risus. Aliquam aliquam augue odio, id euismod eros vestibulum at. Cras ut mauris blandit, viverra dolor eu, scelerisque nisi. Aliquam ultrices volutpat tincidunt. Ut at eros scelerisque, consectetur dui non, ornare felis. Vestibulum sit amet ultrices ligula. Mauris sed libero mollis, laoreet leo ac, elementum est. Proin tincidunt efficitur pulvinar.",
      "Suspendisse eget porta sapien. Morbi et risus eget sapien malesuada laoreet. Integer porttitor tristique pulvinar. In consequat elementum odio sit amet cursus. Vivamus sed elit eget augue facilisis rutrum. Nullam et tristique purus. In congue, risus et rutrum auctor, neque nisi varius sem, placerat volutpat nisi justo id sem. Phasellus dignissim porta neque et ultricies. Morbi a odio egestas, accumsan sapien a, dictum mi.",
      "Sed tincidunt, nibh at vehicula vehicula, leo mi finibus elit, sit amet commodo justo nisi nec nunc. Donec vestibulum ullamcorper mauris, ac faucibus felis varius vitae. Quisque ut est placerat dui malesuada pharetra. Sed tincidunt in quam at molestie. Mauris lobortis ex sit amet purus faucibus ultricies nec in massa. Mauris viverra interdum dolor, convallis vulputate lacus ullamcorper a. Fusce mattis rutrum mi, nec gravida dui feugiat interdum. Donec eget sem lacinia, eleifend elit non, consectetur orci.",
      "Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce at orci sit amet dolor aliquet aliquet. Etiam hendrerit quam quis neque malesuada egestas. Nam vel est lacinia, pellentesque tortor eget, scelerisque est. Suspendisse potenti. Donec vehicula interdum egestas. Aenean facilisis, ipsum id ornare sagittis, odio leo consectetur velit, at maximus nunc metus a elit.",
      "Aenean id ante sit amet risus aliquet lacinia. Donec eget leo id lorem accumsan efficitur. Donec arcu lorem, ultrices nec urna et, cursus ultricies massa. Phasellus ac elementum orci. Sed at velit a lacus sollicitudin imperdiet vulputate a metus. Ut feugiat, odio a cursus tempus, purus magna tempus metus, tempor tempus leo ligula et erat. Morbi condimentum diam at libero aliquam, in molestie purus gravida. Vestibulum volutpat nec nisl nec iaculis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum scelerisque elit, non ultrices felis porttitor ac. Praesent mauris magna, cursus scelerisque elementum non, lobortis eget mi. Aliquam a lacinia libero. Fusce mollis mauris ut congue convallis.",
      "Aliquam erat volutpat. Aliquam magna justo, blandit finibus nisi sed, ultricies elementum mi. Phasellus non arcu in turpis aliquet bibendum. Ut ac arcu at risus interdum mollis a eu sapien. Quisque posuere risus eget odio volutpat lobortis. Pellentesque in porta arcu, ut tempus leo. Ut facilisis maximus efficitur. Donec sit amet elit in ipsum congue iaculis id quis nulla.",
      "Cras lectus lacus, dignissim quis nisl et, dignissim euismod neque. Mauris luctus, velit ac congue sagittis, lacus elit iaculis nunc, in pulvinar felis lectus eu nisl. Ut laoreet in quam et semper. Fusce suscipit condimentum luctus. Aenean congue massa turpis, in bibendum orci interdum eget. Donec est massa, lobortis vel maximus at, dapibus et nibh. Integer mattis est eget velit luctus maximus. Pellentesque pretium accumsan leo, sed porta ex pharetra a. Suspendisse potenti. Maecenas vitae purus purus. Etiam pulvinar odio a tincidunt laoreet. Donec non ultrices turpis, nec ullamcorper odio. Vivamus condimentum massa vitae dolor vehicula, at luctus neque dignissim.",
      "Cras tincidunt posuere nibh ut cursus. Donec sodales velit urna, vitae aliquet ipsum euismod id. Sed ultricies laoreet turpis, vitae gravida tellus volutpat vitae. Aliquam id ipsum eget quam aliquet eleifend at eu metus. Fusce nisi nisl, accumsan vel suscipit sed, lacinia non massa. Maecenas at velit tellus. Fusce luctus, ligula et elementum aliquet, odio velit lacinia arcu, vel condimentum dolor enim eu purus. Cras maximus, dolor ac interdum vehicula, quam felis laoreet arcu, eget malesuada odio dolor ac quam. Quisque a convallis tellus, eget venenatis nisl. Mauris iaculis justo ac condimentum ullamcorper. Donec vel lectus posuere, lacinia mauris non, suscipit nisl. Vivamus quis lorem felis. Quisque luctus volutpat cursus.",
      "Sed porta, purus eget feugiat elementum, risus lacus vestibulum justo, et dignissim quam mi molestie nisi. Maecenas sed risus bibendum, porttitor sapien non, finibus odio. Integer eget neque sed diam porta porttitor. Nunc nec dolor ac ligula malesuada imperdiet. Duis convallis velit eu nisi rhoncus venenatis. Nulla blandit arcu eget dictum mollis. Nulla non dapibus enim, nec finibus massa. Pellentesque iaculis ultrices vehicula. Cras dignissim condimentum velit et varius. Proin at elit fringilla, lobortis augue ac, laoreet metus. Etiam pharetra gravida enim, in ultrices magna luctus nec. Fusce luctus nibh ac arcu viverra, id rutrum tortor rhoncus. Nam convallis quam erat, at aliquet elit congue id. Nunc pharetra maximus mi, id fermentum metus eleifend sit amet.",
      "Praesent et efficitur arcu, vel vestibulum urna. Duis aliquam ligula eros, feugiat luctus tellus commodo sit amet. Nulla ultrices gravida nisi, a congue lacus elementum id. Integer posuere felis mollis, euismod libero volutpat, porta erat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed congue consectetur ex. Maecenas a libero sed lorem cursus blandit vitae eu enim. Duis porttitor in sapien nec suscipit. Nulla lacinia, nulla at rhoncus posuere, leo justo gravida nisl, quis mollis nisi lacus non nisl. Sed consectetur ante nulla, a scelerisque ex congue sed. Aliquam a orci iaculis, congue libero a, tempus velit.",
      "Ut vel eros nec arcu pellentesque tempus eget vel lacus. Aenean tristique ut lacus in suscipit. Proin eget pulvinar elit. Aenean felis ante, sollicitudin sed turpis vel, feugiat rhoncus urna. Mauris pellentesque quis nulla vitae varius. Donec nulla velit, facilisis at nisi id, vestibulum tempor lorem. Nullam semper, nibh id placerat vulputate, velit mi blandit ante, vel tincidunt purus mi at mi. In efficitur urna lectus, eget dignissim ligula vulputate in. Morbi nec ultrices magna, at rhoncus orci. Donec varius gravida tortor in luctus.",
      "Nunc dignissim ut risus in facilisis. Aliquam ullamcorper velit non elit cursus tincidunt. Curabitur condimentum arcu sed felis consectetur ultricies. Suspendisse eget finibus sem. Sed nisl augue, tempus et condimentum eget, gravida et eros. Donec elementum lacus mi, a convallis lorem pellentesque eu. Nam non orci non tortor sollicitudin pharetra nec ac dui. Fusce pharetra dui non ante accumsan, et aliquet metus tincidunt. Cras blandit nec diam et dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse sodales orci vel placerat tempus. Sed maximus sollicitudin lorem, vel sagittis lacus faucibus nec. Nunc neque augue, sagittis a vestibulum ut, hendrerit sit amet ex.",
      "Nulla non eros egestas neque volutpat aliquam eu eget erat. Sed rhoncus urna dolor. Sed semper est turpis, ut lacinia enim laoreet ut. Donec sed orci rutrum dolor scelerisque posuere sit amet ut libero. Suspendisse potenti. Donec eget risus posuere, semper mauris in, vehicula enim. Nullam nulla nisl, sodales eget felis eget, bibendum pellentesque tellus. Nulla viverra leo nunc, ullamcorper viverra enim dapibus nec. Etiam ac nulla maximus, sollicitudin mauris varius, elementum elit. Nunc ut iaculis risus. Fusce imperdiet, dolor ut congue molestie, elit risus mattis nisl, ut mattis ipsum lorem at leo.",
      "Nam posuere fermentum velit, eget ullamcorper ligula vulputate in. Etiam tempus eros eget ante scelerisque, id vestibulum tortor ornare. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent at tincidunt augue, ac suscipit neque. Donec non purus volutpat, ultricies diam id, rutrum nunc. Curabitur nisi augue, scelerisque id lacinia ut, maximus rhoncus nibh. Ut nec tempus libero. Nullam aliquam purus id vulputate viverra. Curabitur pulvinar, ligula ut mattis congue, nisl lorem semper ante, in laoreet lorem mauris vel tellus. Proin blandit dictum hendrerit. Nulla malesuada purus non magna viverra rutrum. Mauris sed ex eu magna ornare ullamcorper in eget tellus. Ut ac mollis metus.",
      "Duis malesuada scelerisque erat, sit amet vulputate ex auctor sit amet. Mauris fermentum posuere ultricies. Aliquam cursus, metus sit amet hendrerit tempor, dui dolor tristique ex, ut pellentesque arcu ligula et ante. Donec tortor tellus, consequat vel massa id, eleifend scelerisque nunc. Pellentesque fermentum non turpis ac accumsan. Duis sit amet pretium lacus. Phasellus quis cursus velit. Duis at placerat eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam a lectus quis leo porta ornare nec et augue. Vestibulum eget orci nec enim aliquet gravida.",
      "Quisque sodales ipsum dolor, vitae vehicula ligula suscipit nec. Pellentesque vel eros bibendum, facilisis sapien eu, laoreet justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec finibus ullamcorper metus, iaculis viverra eros interdum et. Sed a viverra nunc. Mauris eu commodo augue. Phasellus vestibulum ullamcorper libero, ut consequat tortor bibendum vel. Pellentesque auctor libero diam, et iaculis turpis blandit eget. In hac habitasse platea dictumst. Curabitur posuere velit id sem imperdiet, eget tincidunt eros hendrerit. Ut facilisis tempor erat ut vestibulum. Nam a diam eget nisi egestas sagittis. Aenean quam nulla, varius a lorem nec, mattis rutrum nunc. Sed vehicula finibus mauris nec egestas. Pellentesque congue magna ut eros congue, quis auctor velit lobortis.",
      "Etiam tincidunt quam sed justo congue, et elementum urna congue. Vivamus at est molestie, euismod ex eget, tincidunt mauris. Cras varius, urna et auctor cursus, ligula sem laoreet tortor, sollicitudin imperdiet tellus nisl eget ex. Ut mi arcu, dictum a pharetra a, sollicitudin id lorem. Aenean nisi urna, semper sed pretium eget, facilisis sed libero. Vestibulum blandit odio diam, ac fermentum eros dignissim vel. Praesent vitae nisl faucibus, semper ex id, maximus sapien. Mauris non sodales nibh, non blandit ligula.",
      "Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum tincidunt sed mauris ac laoreet. Quisque ultrices mauris nec dui bibendum maximus. Duis imperdiet nunc urna, sit amet dictum diam viverra id. Praesent varius, nisl sed fermentum aliquet, arcu lectus malesuada ipsum, vel condimentum arcu sem at urna. Ut scelerisque quam justo, vel pellentesque ipsum scelerisque a. Vivamus in libero vel felis bibendum consectetur. Nam sollicitudin tellus tristique lorem rhoncus gravida. Morbi congue turpis enim, vel feugiat dui tempus vel. Maecenas suscipit felis enim, vel malesuada velit sollicitudin id.",
      "Sed porttitor metus odio, eu commodo elit faucibus id. In quis quam iaculis, elementum ligula in, consequat lacus. Donec lobortis condimentum fermentum. Integer suscipit, dolor ut pharetra tincidunt, augue lacus vestibulum est, ac vehicula ipsum ligula vel odio. Morbi efficitur eu urna ullamcorper egestas. Cras leo ex, aliquet vitae leo ac, tempus convallis nibh. Praesent porttitor, nunc at facilisis dapibus, leo turpis malesuada turpis, in aliquam quam quam porta tortor. Aliquam porttitor dolor vitae pretium tempus. Fusce non lacus lectus. Donec venenatis efficitur hendrerit. Cras velit ipsum, placerat vel vulputate ut, facilisis sit amet arcu. Nunc dictum erat est, vitae finibus neque tristique in. Phasellus enim leo, luctus eu fringilla ac, viverra non ex. Sed vulputate augue ut quam venenatis blandit.",
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit turpis iaculis massa facilisis, interdum tristique purus maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus. In placerat est ut cursus sagittis. Nam non quam tellus. Mauris et lorem ex. Fusce vitae turpis auctor, venenatis nunc eget, molestie lacus. Duis dolor dolor, interdum ut erat vel, pretium venenatis turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eros dolor, dignissim vitae auctor sit amet, consequat et risus. Suspendisse dignissim tempus mauris, sed lobortis urna vulputate vel.",
      "Nam nec commodo mi, eget congue mauris. Cras id diam dolor. Fusce consectetur a nisl at sagittis. Phasellus a lorem sit amet tortor dictum ornare sed non sapien. Nullam nisi lorem, consequat a iaculis sit amet, euismod ut neque. Donec faucibus justo sed pulvinar accumsan. Cras at accumsan mauris, placerat dapibus lectus. Duis et orci nec risus consectetur consequat congue a nulla. Morbi imperdiet, lectus id ultricies finibus, sem diam vestibulum neque, sit amet bibendum ipsum velit ut ipsum. In bibendum, nibh non convallis dictum, lorem velit elementum leo, ut congue neque velit at risus. Etiam id justo dapibus, molestie tellus nec, convallis mi. Cras vitae lacinia libero. Curabitur iaculis lacus tristique ex luctus, ac volutpat ante mollis. Proin nec ipsum quis nunc porta cursus vitae vitae est.",
      "In imperdiet pretium elit, nec blandit sem sollicitudin vitae. Pellentesque a tellus felis. Ut congue, massa ac viverra viverra, mi nisi pulvinar ipsum, non eleifend neque nisl mattis mauris. Ut ut gravida dolor. Pellentesque laoreet ac neque a condimentum. Sed posuere est at felis aliquet, eget commodo massa sollicitudin. Nam sodales risus eu semper vulputate. Pellentesque tempus eget orci ac cursus. Phasellus justo ex, dictum vitae pellentesque at, mattis at tortor.",
      "Donec aliquam risus eu magna tempor dictum. Integer nisl dolor, pellentesque eu turpis ut, mattis eleifend mi. Mauris eget tortor id ante fermentum mattis ac ac metus. Proin ut erat vitae leo consequat congue. Ut tincidunt at libero quis imperdiet. Suspendisse aliquam, risus sit amet maximus hendrerit, turpis metus maximus enim, quis convallis risus odio in mauris. Donec efficitur nisi vitae elit sollicitudin condimentum. Nam consequat rutrum erat, et ornare dui fermentum efficitur. Ut eget vehicula quam. Proin iaculis dignissim turpis, eget viverra nunc vestibulum eget."
   ];
}

// Method to the GenerateNewText constructor function that generates a random sentence
GenerateNewText.prototype.getRandomSentence = function() {
  let randomSentence = this.sentences[Math.floor(Math.random() * this.sentences.length)]
	return randomSentence;
}

// Method to the GenerateNewText constructor function that generates a paragraph from random sentences
GenerateNewText.prototype.getParagraph = function() {
  let paragraph = "";
  // Set the minimum number of words
  let minimumCharacterLength = 250;
  let firstSentence = true;
  while (paragraph.length < minimumCharacterLength) {
    if (firstSentence) {
      paragraph = paragraph.concat(this.getRandomSentence());
      firstSentence = false;
    } else {
      paragraph = paragraph.concat(" " + this.getRandomSentence());
    }
  }
  return paragraph;
}

// Method to the GenerateNewText constructor function that gerates multiple paragraphs from paragraphs
GenerateNewText.prototype.getAllParagraphs = function(numberOfParagraphs) {
  let allParagraphs = [];
  // Generate the number of paragraphs as specified by the user
  while (allParagraphs.length < numberOfParagraphs) {
    allParagraphs.push(this.getParagraph());
  }
  // Convert array into HTML string
  let paragraphHTML = "";
  allParagraphs.forEach(function (paragraph) {
    paragraphHTML += "<p>" + paragraph + "</p>";
  });
  return paragraphHTML;
}

module.exports = loremIpsum;
